#import "../env/lib.typ": *

= Lecture 7: Scattering Theory II: Symmetry

This section we want to talk about the symmetry of the scattering
theory, which is a very important topic. For a symmetry covariant
quantum theory, every symmetry should be related to a Unitary
operator:
$
    U
$
For a scattering theory, when we say it is some symmetry invariant, we
mean that:
#definition[Symmetry of Scattering Theory][
    The *same* symmetry operator $U$ act on *both in and out*
    asymptotic states as the corresponding symmetry operator of the
    free theory act on free particle states, which means that:
    $
        U|psi^plus.minus_alpha angle.r tilde U_0|phi.alt_alpha angle.r
    $
]
Notice that this is a stronger condition that requiring the theory to
have some symmetry.

This section we will focus on, if we assume that the scattering theory
has some symmetry (which should be the case for a theory we want).
What are the consequences of this symmetry?


== Poincare Symmetry

We focus on scaler field theory for simplicity, thus the free theory
states are labed by momentums $|{p_i} angle.r$, and we use the
notation $|{k_i}^plus.minus angle.r$ for asymptotic states. The
poincare symmetry is generated by $U(Lambda, a)$. With a theory of
this symmetry, we have:
$
    U_0(Lambda, a)|{p_i} angle.r = e^(i sum_i p_i^mu a_nu Lambda^nu_mu) |{Lambda p_i} angle.r \
    U (Lambda, a)|{k_i}^plus.minus angle.r = e^(i sum_i k_i^mu a_nu Lambda^nu_mu) |{Lambda k_i}^plus.minus angle.r
$
Here let's focus on its consquences.

=== Translation Invariance and Momentum Conservation

We plug in a $U(Lambda,a)$ in the definition of the S matrix element:
$
    S({p_i},{k_i}) = e^(i sum_i p_i^mu a_nu Lambda^nu_mu) e^(- i sum_i k_i^mu a_nu Lambda^nu_mu) S({Lambda p_i}, {Lambda k_i})
$
The LHS is independent of $a$, if we take $Lambda = I$ thus we must
have:
$
    sum_i p_i^mu = sum_i k_i^mu
$
This shows that:

- The Translation Invariance of the scattering theory implies the
    conservation of the total momentum.

Thus the S matrix element can be written as a stronger form in a
translational invariant theory:
$
    S_( beta alpha ) = delta_( alpha beta ) - ( 2 pi )^( 4 ) delta^( ( 4 ) ) ( P_( f ) - P_( i ) ) i cal(M)_( beta )
$
where $P_( f )$ and $P_( i )$ are the total momentum of the final and
initial states, and $cal(M)_( beta )$ is called the *scattering
amplitude*.

=== S Matrix with Full Poincare Symmetry

Then we can further plug in full poincare transformation. we have:
$
    [S, U_0(Lambda, a)] = 0
$
The deduction is straightforward from definition. We can define the
generators of the Poincare group in the free and full interacting
theory as:
$
    & G_0 = (H_0, P_0, J_0, K_0) \
    & G = (H, P, J, K)
$
then we simply have:
$
    [S, G_0] = 0
$
In fact, we can further deduce a relation between the generators and
Moller operators:
$
    G Omega_plus.minus = Omega_plus.minus G_0
$

=== Generator of Symmetry

In fact in a *Typical Interacting Theory*, the generators of the
symmetry in the full interacting theory are in the following relation
with the generators in the free theory:
$
    H = H_0 + H_I
    quad P = P_0
    quad J = J_0
    quad K = K_0 + Delta K
$
Now if we assume this holds, we can further deduce some results:
$
    [J_0, H_I] = [P_0, H_I] = 0
$
and for boost generator, we have:
$
    [K,H_I] + [Delta K, H_0] = 0
$
